### ISSUE TITLE
Not compatible with Rails 7.1

### ISSUE THREAD

**Issue by tomukas** [westonganger/protected_attributes_continued#29]
```
/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/protected_attributes_continued-1.8.2/lib/active_record/mass_assignment_security.rb:24:in `<top (required)>': superclass mismatch for class SchemaMigration (TypeError)
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/protected_attributes_continued-1.8.2/lib/protected_attributes.rb:6:in `block in <top (required)>'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/lazy_load_hooks.rb:77:in `each'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.0/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/base.rb:338:in `<module:ActiveRecord>'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/base.rb:15:in `<top (required)>'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/delayed_job_active_record-4.1.7/lib/delayed/backend/active_record.rb:33:in `<module:ActiveRecord>'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/delayed_job_active_record-4.1.7/lib/delayed/backend/active_record.rb:6:in `<module:Backend>'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/delayed_job_active_record-4.1.7/lib/delayed/backend/active_record.rb:5:in `<module:Delayed>'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/delayed_job_active_record-4.1.7/lib/delayed/backend/active_record.rb:4:in `<top (required)>'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/delayed_job_active_record-4.1.7/lib/delayed_job_active_record.rb:5:in `<top (required)>'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:55:in `each'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:55:in `block in require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:44:in `each'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/runtime.rb:44:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler.rb:196:in `require'
	from /Users/tomas/projects/tax/config/application.rb:7:in `<top (required)>'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/commands/server/server_command.rb:139:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/commands/server/server_command.rb:136:in `perform'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command/base.rb:73:in `perform'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command.rb:71:in `block in invoke'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command.rb:149:in `with_argv'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command.rb:69:in `invoke'
	from /Users/tomas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/commands.rb:18:in `<top (required)>'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/tomas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by westonganger** [comment]
v1.9.0 is now released which fixes this.
